CREATE TABLE STUDENT(
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    HOMETOWN TEXT,
    PHONE_IND INTEGER,
    AGE INTEGER
);

INSERT INTO STUDENT (ROLL_NO, NAME, HOMETOWN, PHONE_IND, AGE) VALUES
    ('1', 'PAARTHU', 'CHANDRAGIRI', 9381660858, 11),
    ('2', 'ME_RITVIK', 'MUMBAI', 7995772407, 11),
    ('3', 'DEVI SRI PRASAD', 'TIRUPATI', 9000438433, 11),
    ('4', 'SAI KRISHNA', 'HYD', 9985213035, 11),
    ('5', 'EKANATH', 'HYD', 9346275791, 11);

SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AGE = 11 AND HOMETOWN = 'MUMBAI';
SELECT * FROM STUDENT WHERE AGE = 11 AND NAME = 'PAARTHU';
SELECT * FROM STUDENT WHERE NAME = 'DEVI SRI PRASAD' OR NAME = 'ME_RITVIK';
SELECT * FROM STUDENT WHERE NAME = 'SAI KRISHNA' OR AGE = 11;
SELECT * FROM STUDENT WHERE AGE = 11 AND (NAME = 'ME_RITVIK' OR NAME = 'EKANATH');